/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package processmining.gui;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author Humanoide
 */
public class GraphFrame extends javax.swing.JFrame {

    /**
     * Creates new form GraphFrame
     */
    public GraphFrame() {
        initComponents();
    }
    BufferedImage bufImg;
    String imageName;
    int cont=0;
    Timer t;
    public GraphFrame(String imageName) {
        this();
        this.imageName = imageName;
        this.setTitle(imageName);
        JLabel label = new JLabel();
        try {
            bufImg = ImageIO.read(new File(imageName + ".png"));
            bufImg.flush();
            label.setIcon(new ImageIcon(bufImg));
            label.setSize(bufImg.getWidth(), bufImg.getHeight());
            this.setSize(bufImg.getWidth(), bufImg.getHeight());
            label.repaint();
            //works even without repaint
        } catch (IOException ex) {
            System.out.println("Unable to read image file");
        }
        
        t=new javax.swing.Timer(200, new ActionListener() {
            @Override
            public void actionPerformed(final ActionEvent e) {
                //do an icon change
                try {
                    bufImg = ImageIO.read(new File(imageName + ".png"));
                    bufImg.flush();
                    label.setIcon(new ImageIcon(bufImg));
                    label.setSize(bufImg.getWidth(), bufImg.getHeight());
                    resize();
                    label.repaint();
                    //works even without repaint
                } catch (IOException ex) {
                    System.out.println("Unable to read image file");
                }
                cont++;
                if(cont<=2){
                    t.stop();
                }
            }
        });
        
        t.start();
       // this.setSize(bufImg.getWidth(), bufImg.getHeight());
        this.add(label);
        this.setVisible(true);
    }
    
    public void resize(){
        this.setSize((int)(bufImg.getWidth()*1.1), (int)(bufImg.getHeight()*1.1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
